# Generated by Django 3.2.7 on 2021-09-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='location',
            new_name='address',
        ),
    ]
